services:
  touitomamout:
    container_name: "touitomamout"
    build:
      context: . # This will build the image from the source code
    restart: unless-stopped
    env_file: ".env"
    environment:
      - DATABASE_PATH=/data/database.sqlite
    volumes:
      - ./data:/data
