services:
  touitomamout:
    container_name: "touitomamout"
    image: ghcr.io/yamada-sexta/touitomamout-next:latest
    restart: unless-stopped
    env_file: ".env"
    environment:
      - DATABASE_PATH=/data/database.sqlite
    volumes:
      - ./data:/data
